trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: "testvalidation"
    jobs:
      - job: tfValidate
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.12.2'
          - script: |
              terraform init
              terraform validate
      - job: tfPlan
        steps:
          - script: 
              terraform plan -var-file="testvariables.tfvars" -var="subscription_id=$(TEST_SUSBCRIPTION_ID)" -out=tfplan
          - publish: tfplan
            artifact: tfplanfile

  - stage: "testdeployment"
    dependsOn: "testvalidation"
    condition: succeeded()
    jobs:
      - job: tfApply
        steps:
          - download: current
            artifact: tfplanfile
          - script: |
              terraform apply "tfplan" -auto-approve


